import { NetworkPreset } from './types';

export const BUILT_IN_PRESETS: NetworkPreset[] = [
  {
    name: 'Beginner',
    description: 'Simple network with safe defaults. Perfect for learning and small datasets.',
    icon: '🌱',
    difficulty: 'beginner',
    estimatedTime: '20s',
    useCase: 'Learning & Basics',
    config: {
      inputLayers: 2,
      hiddenLayers: [16],
      outputLayers: 3,
      hiddenActivation: 'relu',
      outputActivation: 'softmax',
      lossFunction: 'categoricalCrossentropy',
      optimizer: 'adam',
      learningRate: 0.01,
      epochs: 50,
      batchSize: 32,
      validationSplit: 0.2,
      normalization: 'minmax',
    },
  },
  {
    name: 'Standard (Recommended)',
    description:
      'Production-ready with regularization, early stopping, and class balancing. Best for most tasks.',
    icon: '🌳',
    difficulty: 'intermediate',
    estimatedTime: '45s',
    useCase: 'Classification',
    config: {
      inputLayers: 2,
      hiddenLayers: [64, 32],
      outputLayers: 3,
      hiddenActivation: 'relu',
      outputActivation: 'softmax',
      lossFunction: 'categoricalCrossentropy',
      optimizer: 'adam',
      learningRate: 0.001,
      epochs: 100,
      batchSize: 32,
      validationSplit: 0.2,
      normalization: 'zscore',
    },
  },
  {
    name: 'Deep Learning',
    description:
      'Advanced 4-layer network with full regularization suite. For complex patterns and large datasets.',
    icon: '🌲',
    difficulty: 'advanced',
    estimatedTime: '90s',
    useCase: 'Complex Patterns',
    config: {
      inputLayers: 2,
      hiddenLayers: [128, 64, 32, 16],
      outputLayers: 3,
      hiddenActivation: 'relu',
      outputActivation: 'softmax',
      lossFunction: 'categoricalCrossentropy',
      optimizer: 'adam',
      learningRate: 0.0001,
      epochs: 200,
      batchSize: 64,
      validationSplit: 0.2,
      normalization: 'zscore',
    },
  },
  {
    name: 'Fast Training',
    description: 'Quick experiments with minimal epochs. Good for rapid prototyping and testing.',
    icon: '⚡',
    difficulty: 'beginner',
    estimatedTime: '15s',
    useCase: 'Rapid Prototyping',
    config: {
      inputLayers: 2,
      hiddenLayers: [32],
      outputLayers: 3,
      hiddenActivation: 'relu',
      outputActivation: 'softmax',
      lossFunction: 'categoricalCrossentropy',
      optimizer: 'adam',
      learningRate: 0.01,
      epochs: 30,
      batchSize: 16,
      validationSplit: 0.2,
      normalization: 'minmax',
    },
  },
];
